[nitpick.meta]
name = "Default python library style file for Nitpick"

[nitpick.styles]
include = [
    "../any/absent.toml",
    "../any/present.toml",
    "../any/prettier.toml",
    "../python/black.toml",
    "../python/pre-commit-hooks.toml",
]
