[nitpick.meta]
name = "Files that should not exist"

[nitpick.files.absent]
".isort.cfg" = "Move values to setup.cfg, section [isort]"
".pyup.yml" = "Configure safety instead: https://github.com/pyupio/safety#using-safety-with-a-ci-service"
"Makefile.inc" = "Use Makefile only"
".scaraplate.conf" = "Use nitpick"