# https://github.com/andreoliwa/nitpick/blob/develop/src/nitpick/resources/python/black.toml

[nitpick.meta]
name = "Black"
url = "https://github.com/psf/black"

["pyproject.toml".tool.black]
line-length = 120

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/psf/black"

[[".pre-commit-config.yaml".repos.hooks]]
id = "black"
args = ["--safe", "--quiet"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/adamchainz/blacken-docs"

[[".pre-commit-config.yaml".repos.hooks]]
id = "blacken-docs"
additional_dependencies = ["black==23.3.0"]