[nitpick.meta]
name = "isort"
url = "https://github.com/PyCQA/isort"

["pyproject.toml".tool.isort]
profile = "black"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/isort"

[[".pre-commit-config.yaml".repos.hooks]]
id = "isort"