[nitpick.meta]
name = "pre-commit hooks for Python projects"
url = "https://pre-commit.com/hooks"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/pygrep-hooks"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-check-mock-methods"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-use-type-annotations"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-check-blanket-noqa"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-check-blanket-type-ignore"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-no-eval"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-no-log-warn"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"

[[".pre-commit-config.yaml".repos.hooks]]
id = "debug-statements"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/ecugol/pre-commit-hooks-django"

[[".pre-commit-config.yaml".repos.hooks]]
id = "check-untracked-migrations"
